const Queries = {
  Books: {
    Create:
      "CREATE TABLE IF NOT EXISTS BOOKS(ID INTEGER PRIMARY KEY AUTOINCREMENT, TITLE TEXT, DESCRIPTION TEXT, ISBN TEXT, AUTHORS TEXT, PUBLISHER TEXT, PAGES INTEGER, CATEGORIES TEXT, THUMB TEXT, YEAR INTEGER, STATUS INTEGER)",
    Insert:
      "INSERT INTO BOOKS (TITLE, DESCRIPTION, ISBN, AUTHORS, PUBLISHER, PAGES, CATEGORIES, THUMB, YEAR, STATUS) VALUES (?,?,?,?,?,?,?,?,?,?)",
    Update:
      "UPDATE BOOKS SET TITLE = ?, DESCRIPTION = ?, ISBN = ?, AUTHORS = ?, PUBLISHER = ?, PAGES = ?, CATEGORIES = ?, THUMB = ?, YEAR = ?, STATUS = ? WHERE ID = ?",
    Delete: "DELETE FROM BOOKS WHERE ID = ?",
    SelectAll:
      "SELECT ID, TITLE, DESCRIPTION, ISBN, AUTHORS, PUBLISHER, PAGES, CATEGORIES, THUMB, YEAR, STATUS FROM BOOKS",
    SelectOne:
      "SELECT ID, TITLE, DESCRIPTION, ISBN, AUTHORS, PUBLISHER, PAGES, CATEGORIES, THUMB, YEAR, STATUS FROM BOOKS WHERE ID = ?",
  },
};
